import type { SnowGear } from '@/types/gear';

export const snowRaceDeepSnowGear: Array<SnowGear> = [
  {
    brand: 'nitro',
    hash: 'e4b485f7',
    kind: 'SB',
    model: 'Mountain X Grif',
    score: 900,
    stats: {
      'speed': 78,
      'air-rotation': 25,
      'deep-snow': 80,
      'absorption': 85,
    },
  },
  {
    brand: 'armada',
    hash: 'e4477437',
    kind: 'SK',
    model: 'Zero Declivity X',
    score: 900,
    stats: {
      'speed': 78,
      'air-rotation': 25,
      'deep-snow': 80,
      'absorption': 85,
    },
  },
  {
    brand: 'rossignol',
    hash: 'd971f3ec',
    kind: 'SB',
    model: 'SNB XV XDLR',
    score: 900,
    stats: {
      'speed': 73,
      'air-rotation': 25,
      'deep-snow': 85,
      'absorption': 85,
    },
  },
  {
    brand: 'faction',
    hash: 'e74c67a2',
    kind: 'SK',
    model: 'Dictator 4.0',
    score: 900,
    stats: {
      'speed': 73,
      'air-rotation': 25,
      'deep-snow': 85,
      'absorption': 85,
    },
  },
  {
    brand: 'rossignol',
    hash: '428a6f25',
    kind: 'SK',
    model: 'Sender 106 TI Plus',
    score: 900,
    stats: {
      'speed': 79,
      'air-rotation': 25,
      'deep-snow': 79,
      'absorption': 85,
    },
  },
  {
    brand: 'nidecker',
    hash: '72586681',
    kind: 'SB',
    model: 'Tracer',
    score: 805,
    stats: {
      'speed': 73,
      'air-rotation': 25,
      'deep-snow': 78,
      'absorption': 80,
    },
  },
  {
    brand: 'atomic',
    hash: '7f44a1d2',
    kind: 'SK',
    model: 'Bent Chetler 120',
    score: 805,
    stats: {
      'speed': 73,
      'air-rotation': 25,
      'deep-snow': 78,
      'absorption': 80,
    },
  },
  {
    brand: 'salomon',
    hash: '13891ed9',
    kind: 'SB',
    model: 'Stance 96',
    score: 855,
    stats: {
      'speed': 76,
      'air-rotation': 25,
      'deep-snow': 79,
      'absorption': 80,
    },
  },
];
