import type { BikeGear } from '@/types/gear';

export const bmxParkGear: Array<BikeGear> = [
  {
    brand: 'cult',
    hash: '4cb2b804',
    model: "Heaven's Gate Begin",
    score: 900,
    stats: {
      'sprint': 42,
      'speed': 38,
      'air-rotation': 90,
      'grip': 15,
      'absorption': 45,
    },
  },
  {
    brand: 'federal',
    hash: '2505af35',
    model: 'Boyd ICS2 Cream',
    score: 900,
    stats: {
      'sprint': 39,
      'speed': 38,
      'air-rotation': 89,
      'grip': 15,
      'absorption': 45,
    },
  },
  {
    brand: 'federal',
    hash: '3ef3094e',
    model: 'Lacey Mauve',
    score: 900,
    stats: {
      'sprint': 40,
      'speed': 40,
      'air-rotation': 90,
      'grip': 15,
      'absorption': 45,
    },
  },
  {
    brand: 'kink',
    hash: '4d574d67',
    model: 'Crosscut Black',
    score: 900,
    stats: {
      'sprint': 38,
      'speed': 42,
      'air-rotation': 89,
      'grip': 30,
      'absorption': 40,
    },
  },
  {
    brand: 'tallorder',
    hash: '5717d3c9',
    model: 'Cranmer 195 Orange',
    score: 900,
    stats: {
      'sprint': 38,
      'speed': 42,
      'air-rotation': 90,
      'grip': 15,
      'absorption': 45,
    },
  },
  {
    brand: 'rr',
    hash: 'c095ff9a',
    model: 'Mummy Bike',
    score: 900,
    stats: {
      'sprint': 39,
      'speed': 40,
      'air-rotation': 90,
      'grip': 30,
      'absorption': 40,
    },
  },
  {
    brand: 'prada',
    hash: 'fce77428',
    model: 'Optical BMX',
    score: 850,
    stats: {
      'sprint': 39,
      'speed': 40,
      'air-rotation': 86,
      'grip': 30,
      'absorption': 40,
    },
  },
];
