import type { SnowGear } from '@/types/gear';

export const snowTricksOffTrackGear: Array<SnowGear> = [
  {
    brand: 'nitro',
    hash: 'fd17e86f',
    kind: 'SB',
    model: 'Victoria',
    score: 900,
    stats: {
      'speed': 50,
      'air-rotation': 65,
      'deep-snow': 80,
      'absorption': 85,
    },
  },
  {
    brand: 'armada',
    hash: '932d8865',
    kind: 'SK',
    model: 'Magic J',
    score: 900,
    stats: {
      'speed': 50,
      'air-rotation': 65,
      'deep-snow': 80,
      'absorption': 85,
    },
  },
  {
    brand: 'nitro',
    hash: '94283353',
    kind: 'SB',
    model: 'Santoku',
    score: 900,
    stats: {
      'speed': 45,
      'air-rotation': 65,
      'deep-snow': 85,
      'absorption': 85,
    },
  },
  {
    brand: 'atomic',
    hash: '048ae78d',
    kind: 'SK',
    model: 'Bentchelter 100',
    score: 900,
    stats: {
      'speed': 45,
      'air-rotation': 65,
      'deep-snow': 85,
      'absorption': 85,
    },
  },
  {
    brand: 'rr',
    hash: '82f79343',
    kind: 'SK',
    model: 'Finish',
    score: 900,
    stats: {
      'speed': 49,
      'air-rotation': 65,
      'deep-snow': 81,
      'absorption': 85,
    },
  },
  {
    brand: 'armada',
    hash: '8e674793',
    kind: 'SK',
    model: 'Armada X Alpine Initiatives JJ',
    score: 900,
    stats: {
      'speed': 49,
      'air-rotation': 64,
      'deep-snow': 82,
      'absorption': 85,
    },
  },
  {
    brand: 'yes',
    hash: '7b768e4c',
    kind: 'SB',
    model: 'PYL',
    score: 840,
    stats: {
      'speed': 52,
      'air-rotation': 62,
      'deep-snow': 75,
      'absorption': 80,
    },
  },
  {
    brand: 'faction',
    hash: '9c2242ff',
    kind: 'SK',
    model: 'CT 5.0',
    score: 840,
    stats: {
      'speed': 52,
      'air-rotation': 62,
      'deep-snow': 75,
      'absorption': 80,
    },
  },
  {
    brand: 'nitro',
    hash: '919cdbd8',
    kind: 'SB',
    model: 'Team Exposure',
    score: 840,
    stats: {
      'speed': 47,
      'air-rotation': 62,
      'deep-snow': 80,
      'absorption': 80,
    },
  },
  {
    brand: 'armada',
    hash: 'd6be0a5e',
    kind: 'SK',
    model: 'ARV 116 JJ 01',
    score: 840,
    stats: {
      'speed': 47,
      'air-rotation': 62,
      'deep-snow': 80,
      'absorption': 80,
    },
  },
  {
    brand: 'nidecker',
    hash: 'e646bbb0',
    kind: 'SB',
    model: 'Lipstick',
    score: 803,
    stats: {
      'speed': 41,
      'air-rotation': 64,
      'deep-snow': 80,
      'absorption': 80,
    },
  },
  {
    brand: 'yes',
    hash: 'fe45097f',
    kind: 'SB',
    model: 'Hel Yes',
    score: 803,
    stats: {
      'speed': 45,
      'air-rotation': 60,
      'deep-snow': 80,
      'absorption': 80,
    },
  },
  {
    brand: 'burton',
    hash: '579ec510',
    kind: 'SB',
    model: 'Custom',
    score: 803,
    stats: {
      'speed': 41,
      'air-rotation': 64,
      'deep-snow': 80,
      'absorption': 80,
    },
  },
  {
    brand: 'rossignol',
    hash: 'a9f1500a',
    kind: 'SK',
    model: 'Sender Squad',
    score: 803,
    stats: {
      'speed': 45,
      'air-rotation': 60,
      'deep-snow': 80,
      'absorption': 80,
    },
  },
  {
    brand: 'armada',
    hash: '105b6785',
    kind: 'SK',
    model: 'Declivity 102',
    score: 803,
    stats: {
      'speed': 41,
      'air-rotation': 64,
      'deep-snow': 80,
      'absorption': 80,
    },
  },
];
