import type { SnowGear } from '@/types/gear';

export const snowTricksSnowParkGear: Array<SnowGear> = [
  {
    brand: 'nitro',
    hash: 'e6af3066',
    kind: 'SB',
    model: 'Beast',
    score: 900,
    stats: {
      'speed': 57,
      'air-rotation': 72,
      'deep-snow': 30,
      'absorption': 55,
    },
  },
  {
    brand: 'armada',
    hash: '4df200bf',
    kind: 'SK',
    model: 'Edollo',
    score: 900,
    stats: {
      'speed': 57,
      'air-rotation': 72,
      'deep-snow': 30,
      'absorption': 55,
    },
  },
  {
    brand: 'lobster',
    hash: 'a8a2c15e',
    kind: 'SB',
    model: 'Lucas Beaufort Artist Edition',
    score: 900,
    stats: {
      'speed': 54,
      'air-rotation': 75,
      'deep-snow': 30,
      'absorption': 55,
    },
  },
  {
    brand: 'faction',
    hash: '25367e61',
    kind: 'SK',
    model: 'Prodigy 2.0 Kengo',
    score: 900,
    stats: {
      'speed': 54,
      'air-rotation': 75,
      'deep-snow': 30,
      'absorption': 55,
    },
  },
  {
    brand: 'kemper',
    hash: '77384850',
    kind: 'SK',
    model: 'Freestyle',
    score: 900,
    stats: {
      'speed': 56,
      'air-rotation': 73,
      'deep-snow': 30,
      'absorption': 55,
    },
  },
  {
    brand: 'prada',
    hash: '23699765',
    kind: 'SB',
    model: 'The Flame Snowboard',
    score: 900,
    stats: {
      'speed': 55,
      'air-rotation': 74,
      'deep-snow': 30,
      'absorption': 55,
    },
  },
  {
    brand: 'gilson',
    hash: '57ba4faa',
    kind: 'SK',
    model: 'SteepSteep',
    score: 900,
    stats: {
      'speed': 55,
      'air-rotation': 74,
      'deep-snow': 30,
      'absorption': 55,
    },
  },
  {
    brand: 'faction',
    hash: '3e67ab9d',
    kind: 'SK',
    model: 'Studio O GU',
    score: 900,
    stats: {
      'speed': 56,
      'air-rotation': 73,
      'deep-snow': 30,
      'absorption': 55,
    },
  },
  {
    brand: 'prada',
    hash: 'fb8e8080',
    kind: 'SK',
    model: 'Prada Faction Prodigy 3.0',
    score: 850,
    stats: {
      'speed': 53,
      'air-rotation': 73,
      'deep-snow': 30,
      'absorption': 54,
    },
  },
  {
    brand: 'yes',
    hash: '06d61cf9',
    kind: 'SB',
    model: 'Greats Uninc',
    score: 805,
    stats: {
      'speed': 48,
      'air-rotation': 75,
      'deep-snow': 30,
      'absorption': 55,
    },
  },
  {
    brand: 'armada',
    hash: '2e6d6d71',
    kind: 'SK',
    model: 'ARV 86 01',
    score: 805,
    stats: {
      'speed': 48,
      'air-rotation': 75,
      'deep-snow': 30,
      'absorption': 55,
    },
  },
  {
    brand: 'burton',
    hash: '518a4ae1',
    kind: 'SB',
    model: 'Good Company',
    score: 900,
    stats: {
      'speed': 55,
      'air-rotation': 75,
      'deep-snow': 30,
      'absorption': 45,
    },
  },
];
