import { Brand } from 'types/brands';
import { CategoryType } from 'types/categories';
import { SnowGearItem } from 'types/gear';
import { SnowTricksSpecType } from 'types/specs';

const gear: Array<SnowGearItem> = [
  {
    brand: Brand.Nitro,
    category: CategoryType.SnowTricks,
    kind: 'SB',
    model: 'Victoria',
    score: 900,
    spec: SnowTricksSpecType.OffTrack,
    stats: {
      speed: 50,
      airRotation: 65,
      deepSnow: 80,
      absorption: 85,
    },
  },
  {
    brand: Brand.Armada,
    category: CategoryType.SnowTricks,
    kind: 'SK',
    model: 'Magic J',
    score: 900,
    spec: SnowTricksSpecType.OffTrack,
    stats: {
      speed: 50,
      airRotation: 65,
      deepSnow: 80,
      absorption: 85,
    },
  },
  {
    brand: Brand.Nitro,
    category: CategoryType.SnowTricks,
    kind: 'SB',
    model: 'Santoku',
    score: 900,
    spec: SnowTricksSpecType.OffTrack,
    stats: {
      speed: 45,
      airRotation: 65,
      deepSnow: 85,
      absorption: 85,
    },
  },
  {
    brand: Brand.Atomic,
    category: CategoryType.SnowTricks,
    kind: 'SK',
    model: 'Bent Chetler 100',
    score: 900,
    spec: SnowTricksSpecType.OffTrack,
    stats: {
      speed: 45,
      airRotation: 65,
      deepSnow: 85,
      absorption: 85,
    },
  },
  {
    brand: Brand.Yes,
    category: CategoryType.SnowTricks,
    kind: 'SB',
    model: 'PYL',
    score: 840,
    spec: SnowTricksSpecType.OffTrack,
    stats: {
      speed: 52,
      airRotation: 62,
      deepSnow: 75,
      absorption: 80,
    },
  },
  {
    brand: Brand.Faction,
    category: CategoryType.SnowTricks,
    kind: 'SK',
    model: 'CT 5.0',
    score: 840,
    spec: SnowTricksSpecType.OffTrack,
    stats: {
      speed: 52,
      airRotation: 62,
      deepSnow: 75,
      absorption: 80,
    },
  },
  {
    brand: Brand.Nitro,
    category: CategoryType.SnowTricks,
    kind: 'SB',
    model: 'Team Exposure',
    score: 840,
    spec: SnowTricksSpecType.OffTrack,
    stats: {
      speed: 47,
      airRotation: 62,
      deepSnow: 80,
      absorption: 80,
    },
  },
  {
    brand: Brand.Armada,
    category: CategoryType.SnowTricks,
    kind: 'SK',
    model: 'ARV 116 JJ 01',
    score: 840,
    spec: SnowTricksSpecType.OffTrack,
    stats: {
      speed: 47,
      airRotation: 62,
      deepSnow: 80,
      absorption: 80,
    },
  },
  {
    brand: Brand.Nidecker,
    category: CategoryType.SnowTricks,
    kind: 'SB',
    model: 'Lipstick',
    score: 803,
    spec: SnowTricksSpecType.OffTrack,
    stats: {
      speed: 41,
      airRotation: 64,
      deepSnow: 80,
      absorption: 80,
    },
  },
  {
    brand: Brand.Yes,
    category: CategoryType.SnowTricks,
    kind: 'SB',
    model: 'Hel Yes',
    score: 803,
    spec: SnowTricksSpecType.OffTrack,
    stats: {
      speed: 45,
      airRotation: 60,
      deepSnow: 80,
      absorption: 80,
    },
  },
  {
    brand: Brand.RR,
    category: CategoryType.SnowTricks,
    kind: '?',
    model: 'The Invitational',
    score: 0,
    spec: SnowTricksSpecType.OffTrack,
    stats: {
      speed: 0,
      airRotation: 0,
      deepSnow: 0,
      absorption: 0,
    },
  },
  {
    brand: Brand.Burton,
    category: CategoryType.SnowTricks,
    kind: 'SB',
    model: 'Custom',
    score: 803,
    spec: SnowTricksSpecType.OffTrack,
    stats: {
      speed: 41,
      airRotation: 64,
      deepSnow: 80,
      absorption: 80,
    },
  },
  {
    brand: Brand.Rossignol,
    category: CategoryType.SnowTricks,
    kind: 'SK',
    model: 'Sender Squad',
    score: 803,
    spec: SnowTricksSpecType.OffTrack,
    stats: {
      speed: 45,
      airRotation: 60,
      deepSnow: 80,
      absorption: 80,
    },
  },
  {
    brand: Brand.Armada,
    category: CategoryType.SnowTricks,
    kind: 'SK',
    model: 'Declivity 102',
    score: 803,
    spec: SnowTricksSpecType.OffTrack,
    stats: {
      speed: 41,
      airRotation: 64,
      deepSnow: 80,
      absorption: 80,
    },
  },
];

export default gear;
