import type { BikeGear } from '@/types/gear';

export const bikeTricksFreerideGear: Array<BikeGear> = [
  {
    brand: 'yt',
    hash: 'e33c82eb',
    model: 'Capra 01',
    score: 900,
    stats: {
      'sprint': 50,
      'speed': 42,
      'air-rotation': 60,
      'grip': 80,
      'absorption': 70,
    },
  },
  {
    brand: 'commencal',
    hash: '4d7f800d',
    model: 'Furious Pef',
    score: 900,
    stats: {
      'sprint': 30,
      'speed': 61,
      'air-rotation': 60,
      'grip': 80,
      'absorption': 80,
    },
  },
  {
    brand: 'specialized',
    hash: '3a67f285',
    model: 'S-Works Epic Evo 01',
    score: 900,
    stats: {
      'sprint': 42,
      'speed': 51,
      'air-rotation': 60,
      'grip': 65,
      'absorption': 75,
    },
  },
  {
    brand: 'cube',
    hash: '719570f0',
    model: 'TW015 HPC',
    score: 900,
    stats: {
      'sprint': 35,
      'speed': 57,
      'air-rotation': 60,
      'grip': 80,
      'absorption': 70,
    },
  },
  {
    brand: 'evil-bikes',
    hash: 'd6ca4c4c',
    model: 'Insurgent',
    score: 900,
    stats: {
      'sprint': 48,
      'speed': 44,
      'air-rotation': 58,
      'grip': 84,
      'absorption': 86,
    },
  },
  {
    brand: 'trek',
    hash: 'ade30058',
    model: 'Session Park',
    score: 900,
    stats: {
      'sprint': 35,
      'speed': 58,
      'air-rotation': 61,
      'grip': 80,
      'absorption': 50,
    },
  },
  {
    brand: 'canyon',
    hash: '62657a66',
    model: 'Torque',
    score: 855,
    stats: {
      'sprint': 38,
      'speed': 55,
      'air-rotation': 54,
      'grip': 80,
      'absorption': 75,
    },
  },
  {
    brand: 'commencal',
    hash: '2c55d287',
    model: 'Furious Kyle Strait 01',
    score: 855,
    stats: {
      'sprint': 44,
      'speed': 49,
      'air-rotation': 54,
      'grip': 80,
      'absorption': 75,
    },
  },
  {
    brand: 'canyon',
    hash: '56b07a05',
    model: 'Strive CF Team 02',
    score: 855,
    stats: {
      'sprint': 39,
      'speed': 52,
      'air-rotation': 56,
      'grip': 80,
      'absorption': 75,
    },
  },
];
