import type { Brand } from '@/types/brands';

export const brandNames = new Map<Brand, string>([
  ['armada', 'Armada'],
  ['atomic', 'Atomic'],
  ['blind-spot', 'Blind Spot'],
  ['bmc', 'BMC'],
  ['burton', 'Burton'],
  ['canyon', 'Canyon'],
  ['commencal', 'Commencal'],
  ['cube', 'Cube'],
  ['cult', 'Cult'],
  ['devinci', 'Devinci'],
  ['evil-bikes', 'Evil Bikes'],
  ['faction', 'Faction'],
  ['federal', 'Federal'],
  ['gilson', 'Gilson'],
  ['gt', 'GT'],
  ['kemper', 'Kemper'],
  ['kink', 'Kink'],
  ['kona', 'Kona'],
  ['lobster', 'Lobster'],
  ['marin', 'Marin'],
  ['mini-logo', 'Mini Logo'],
  ['nidecker', 'Nidecker'],
  ['nitro', 'Nitro'],
  ['pizza', 'Pizza'],
  ['powell-peralta', 'Power Peralta'],
  ['prada', 'Prada'],
  ['rossignol', 'Rossignol'],
  ['rr', 'RR'],
  ['salomon', 'Salomon'],
  ['santa-cruz', 'Santa Cruz'],
  ['shackdaddys', 'ShackDaddys'],
  ['specialized', 'Specialized'],
  ['subrosa', 'Subrosa'],
  ['tallorder', 'Tallorder'],
  ['trek', 'Trek'],
  ['victory', 'Victory Yama'],
  ['wethepeople', 'Wethepeople'],
  ['yes', 'Yes'],
  ['yt', 'YT Industries'],
]);
