import { Brand } from 'types/brands';

export const brandNames = new Map<Brand, string>([
  [Brand.Armada, 'Armada'],
  [Brand.Atomic, 'Atomic'],
  [Brand.BMC, 'BMC'],
  [Brand.Burton, 'Burton'],
  [Brand.Canyon, 'Canyon'],
  [Brand.Commencal, 'Commencal'],
  [Brand.Cube, 'Cube'],
  [Brand.Cult, 'Cult'],
  [Brand.Devinci, 'Devinci'],
  [Brand.EvilBikes, 'Evil Bikes'],
  [Brand.Faction, 'Faction'],
  [Brand.Federal, 'Federal'],
  [Brand.GT, 'GT'],
  [Brand.Kemper, 'Kemper'],
  [Brand.Kink, 'Kink'],
  [Brand.Kona, 'Kona'],
  [Brand.Lobster, 'Lobster'],
  [Brand.Nidecker, 'Nidecker'],
  [Brand.Nitro, 'Nitro'],
  [Brand.Prada, 'Prada'],
  [Brand.RR, 'RR'],
  [Brand.Rossignol, 'Rossignol'],
  [Brand.Salomon, 'Salomon'],
  [Brand.SantaCruz, 'Santa Cruz'],
  [Brand.Specialized, 'Specialized'],
  [Brand.Subrosa, 'Subrosa'],
  [Brand.Tallorder, 'Tallorder'],
  [Brand.Trek, 'Trek'],
  [Brand.Victory, 'Victory Yama'],
  [Brand.Wethepeople, 'Wethepeople'],
  [Brand.YTIndustries, 'YT Industries'],
  [Brand.Yes, 'Yes'],
]);
