import type { BikeGear } from '@/types/gear';

export const bikeTricksSlopestyleGear: Array<BikeGear> = [
  {
    brand: 'commencal',
    hash: '9dbf6b40',
    model: 'Absolut SX 01',
    score: 900,
    stats: {
      'sprint': 53,
      'speed': 50,
      'air-rotation': 75,
      'grip': 30,
      'absorption': 50,
    },
  },
  {
    brand: 'santa-cruz',
    hash: 'a372a8af',
    model: 'Carbon Trials 01',
    score: 900,
    stats: {
      'sprint': 65,
      'speed': 38,
      'air-rotation': 75,
      'grip': 40,
      'absorption': 40,
    },
  },
  {
    brand: 'canyon',
    hash: '27d21ed6',
    model: 'DJ 360 Tomas Lemoine',
    score: 900,
    stats: {
      'sprint': 57,
      'speed': 46,
      'air-rotation': 75,
      'grip': 30,
      'absorption': 50,
    },
  },
  {
    brand: 'gt',
    hash: 'f67e2db3',
    model: 'La Bomba',
    score: 900,
    stats: {
      'sprint': 57,
      'speed': 47,
      'air-rotation': 75,
      'grip': 30,
      'absorption': 40,
    },
  },
  {
    brand: 'trek',
    hash: 'da3defd7',
    model: 'Ticket S',
    score: 900,
    stats: {
      'sprint': 49,
      'speed': 54,
      'air-rotation': 75,
      'grip': 30,
      'absorption': 50,
    },
  },
  {
    brand: 'trek',
    hash: 'da3defd8',
    model: 'Ticket S',
    score: 900,
    stats: {
      'sprint': 50,
      'speed': 54,
      'air-rotation': 74,
      'grip': 30,
      'absorption': 50,
    },
  },
  {
    brand: 'devinci',
    hash: 'ab8d49ba',
    model: 'Sabbath',
    score: 855,
    stats: {
      'sprint': 60,
      'speed': 44,
      'air-rotation': 70,
      'grip': 30,
      'absorption': 41,
    },
  },
  {
    brand: 'yt',
    hash: '7a20805b',
    model: 'Dirtlove 01',
    score: 855,
    stats: {
      'sprint': 62,
      'speed': 42,
      'air-rotation': 70,
      'grip': 30,
      'absorption': 41,
    },
  },
  {
    brand: 'rr',
    hash: 'a25fca6d',
    model: 'Stickerbomb',
    score: 855,
    stats: {
      'sprint': 58,
      'speed': 46,
      'air-rotation': 70,
      'grip': 30,
      'absorption': 41,
    },
  },
];
